import turtle

def draw_flower(ben):
    for i in range (0,2):
        ben.fd(100)
        ben.rt(50)
        ben.fd(100)
        ben.rt(130)

def draw_art():
    window=turtle.Screen()
    window.bgcolor("lightblue")

    art=turtle.Turtle()
    art.color("darkblue")
    art.shape("turtle")
    art.speed(25)
    for i in range (0,72):
        draw_flower(art)
        art.rt(5)
    art.rt(90)
    art.pen(pensize=3)
    art.fd(450)
    art.color("lightblue")
    art.pen(pensize=0)
    art.ht()
    art.lt(90)
    art.fd(150)
    art.color("red")
    art.pen(pensize=5)
    art.lt(90)
    art.fd(100)
    art.rt(90)
    art.fd(50)
    art.bk(100)
    art.fd(50)
    art.rt(90)
    art.fd(100)
    art.pen(pensize=0)
    art.color("lightblue")
    art.lt(90)
    art.fd(10)
    art.color("red")
    art.pen(pensize=5)
    art.circle(1)
    art.color("lightblue")
    art.pen(pensize=0)
    art.fd(110)
    art.color("red")
    art.pen(pensize=5)
    art.lt(90)
    art.fd(100)
    art.rt(90)
    art.fd(50)
    art.bk(100)
    art.fd(50)
    art.rt(90)
    art.fd(100)
    art.color("lightblue")
    art.pen(pensize=0)
    art.lt(90)
    art.fd(10)
    art.color("red")
    art.pen(pensize=5)
    art.circle(1)
    art.pen(pensize=1)
    art.fd(50)
    art.circle(10)
    art.fd(50)
    art.lt(45)
    art.st()
    art.color("darkblue", "red")
    art.shapesize(1,1,2)

    window.exitonclick()

draw_art()
